Kconfig: cve-check: depends on IS_BRANCH_SCARTHGAP
This fixes commit 4b6faf914b3f636da2e11b3678504a2692c65fa1.

The class cve-check was removed since wrynose[1].

This depends on IS_BRANCH_SCARTHGAP as scarthgap is the last maintained
branch supporting it.

Fixes:

	ERROR: Unable to parse /home/gportay/src/meta-downstream/bitbake/lib/bb/parse/parse_py/BBHandler.py
	Traceback (most recent call last):
	  File "/home/gportay/src/meta-downstream/bitbake/lib/bb/parse/parse_py/BBHandler.py", line 81, in inherit
	    raise ParseError("Could not inherit file %s" % (file), fn, lineno)
	bb.parse.ParseError: ParseError in configuration INHERITs: Could not inherit file classes/cve-check.bbclass

	2026-09-26 17:27:48 - ERROR    - Command "/home/gportay/src/meta-downstream/bitbake/bin/bitbake -c build core-image-minimal" failed with error 1

[1]: https://github.com/openembedded/openembedded-core/commit/00de455f8d3aeca880129d23e8cfb7e246404699