Kconfig: meta-rauc-community: select meta-rauc
This selects the meta-rauc layer instead of depending on it[1][2].

Fixes:

	ERROR: Layer 'meta-rauc-qemux86' depends on layer 'rauc', but this layer is not enabled in your configuration

[1]: https://github.com/rauc/meta-rauc-community/commit/45502ba7def9c1047db2968e2956fef727cff658
[2]: https://github.com/rauc/meta-rauc-community/commit/52fb72b4d3ce5ba77474740fa89dca648297e200