meta-downstream: wic: move wks files to files
This fixes commit 4cab0266078e95bc1c363e49b43479e179af6485.

Fixes:

	ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
	    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
	    Following is the list of potential problems / advisories:

	    wic/wks files at /home/gportay/src/meta-downstream/build/../meta-downstream/wic need to be moved to files/wic within the layer to be found/used
	wic/wks files at /home/gportay/src/meta-downstream/build/../meta-downstream/wic need to be moved to files/wic within the layer to be found/used