meta-rauc-raspberrypi: scarthgap: select meta-lts-mixins
This fixes commit ab5c0657a9509ef55b4d0f8a2961c761ae1c920d.

This selects meta-lts-mixins[1] to meta-rauc[2][3] for scarthgap branch.

Fixes:

	ERROR: Layer 'meta-rauc-raspberrypi' depends on layer 'lts-u-boot-mixin', but this layer is not enabled in your configuration

[1]: https://git.yoctoproject.org/meta-lts-mixins/log/?h=scarthgap/u-boot
[2]: https://github.com/rauc/meta-rauc-community/commit/1fd7bc779903985b81b56772bef75ef92b753d09
[3]: https://github.com/rauc/meta-rauc-community/blob/scarthgap/meta-rauc-raspberrypi/conf/layer.conf#L12