Kconfig: qemu: fix missing dependency on qemux86-64
This fixes missing dependency on qemux86-64 if selection another QEMU
machine and dm-verity at the same time.

Fixes:

	ERROR: Nothing RPROVIDES 'intel-microcode' (but /home/gportay/src/meta-downstream/build/../openembedded-core/meta/recipes-core/images/core-image-minimal.bb RDEPENDS on or otherwise requires it)
	intel-microcode was skipped: incompatible with host aarch64-oe-linux (not in COMPATIBLE_HOST)
	NOTE: Runtime target 'intel-microcode' is unbuildable, removing...
	Missing or unbuildable dependency chain was: ['intel-microcode']
	ERROR: Required build target 'core-image-minimal' has no buildable providers.
	Missing or unbuildable dependency chain was: ['core-image-minimal', 'intel-microcode']