Kconfig: meta-security: select meta-oe dependency layer
This fixes commit 74c2effd0715f8efdaec32c7186cb67ea73cd591.

This selects meta-oe if meta-security is selected.

Fixes:

	ERROR: Layer 'security' depends on layer 'openembedded-layer', but this layer is not enabled in your configuration