meta-backport-kirkstone: backport rauc-conf recipe
This backports the recipe rauc-conf from meta-rauc[1].

	rauc: split package into 'rauc' for binary and 'rauc-conf' for configuration

	This allows to build 'rauc' with default TUNE_PKGARCH while only
	'rauc-conf' needs to be build for MACHINE_ARCH as it contains
	MACHINE-specific configuration.

	Another point is that the RAUC configuration may not only by
	MACHINE-specific but may also differ between images (for the same
	MACHINE).

	The rauc target package now RRECOMMENDS rauc-conf to pull this in by
	default.

	For providing your own configuration, either bbappend the existing
	rauc-conf recipe, write a new one that provides 'virtual-rauc-conf' and
	set PREFERRED_PROVIDER_virtual-rauc-conf or just write a custom one and
	add it to your image's IMAGE_INSTALL list (or any packagegroup).

	Either way, this requires migration in your rauc recipe(s)!

Important: That recipe remains *unused* on kirkstone.

Fixes:

	ERROR: No recipes in default available for:
	  /home/gportay/src/meta-downstream/build/../meta-rauc-raspberrypi-firmware/recipes-core/rauc/rauc-conf.bbappend
	NOTE: Runtime target 'vim-xxd' is unbuildable, removing...
	Missing or unbuildable dependency chain was: ['vim-xxd']
	NOTE: Runtime target 'raspberrypi-firmware-systemd-generator' is unbuildable, removing...
	Missing or unbuildable dependency chain was: ['raspberrypi-firmware-systemd-generator', 'vim-xxd']
	ERROR: Required build target 'update-bundle' has no buildable providers.
	Missing or unbuildable dependency chain was: ['update-bundle', 'core-image-minimal', 'raspberrypi-firmware-systemd-generator', 'vim-xxd']

[1]: https://github.com/rauc/meta-rauc/commit/d51bab8f760d48e082f3515606d2d1a18343f5d6