vim: put xxd in its own package
This backports commit[1].

	The xxd tool can be quite handy by itself, and doesn't have anything
	to do with vim per se. Make it possible to include the rather tiny xxd
	in a rootfs without pulling in the several MB vim binary and
	associated data.

	For backwards compatibility, add an RDEPENDS from the main package to
	the new vim-xxd package.

See[2][3].

Fixes:

	ERROR: Nothing RPROVIDES 'vim-xxd' (but
	/home/gportay/src/meta-downstream/build/../meta-rauc-raspberrypi-firmware/recipes-bsp/raspberrypi-firmware-systemd-generator/raspberrypi-firmware-systemd-generator_git.bb
	RDEPENDS on or otherwise requires it)

[1]: https://git.openembedded.org/openembedded-core/commit/meta/recipes-support/vim?id=06ed2aa93fc25a681e3a00ee120d9395b04845da
[2]: https://git.openembedded.org/openembedded-core/tree/meta/recipes-support/vim/vim_9.1.bb?h=kirkstone
[3]: https://git.openembedded.org/openembedded-core/tree/meta/recipes-support/vim/vim_9.1.bb?h=scarthgap