rpi-autoboot: drop uneeded UNPACKDIR variable
This fixes commit 6f11521ef7184f79802ff92739b325412df5e72f.

Fixes:

	ERROR: rpi-autoboot-1.0-r1 do_deploy: ExecutionError('/home/gportay/src/meta-downstream/build/tmp/work/raspberrypi4_64-poky-linux/rpi-autoboot/1.0-r1/temp/run.do_deploy.186176', 1, None, None)
	ERROR: Logfile of failure stored in: /home/gportay/src/meta-downstream/build/tmp/work/raspberrypi4_64-poky-linux/rpi-autoboot/1.0-r1/temp/log.do_deploy.186176
	Log data follows:
	| DEBUG: Executing python function sstate_task_prefunc
	| DEBUG: Python function sstate_task_prefunc finished
	| DEBUG: Executing shell function do_deploy
	| cp: cannot stat '/home/gportay/src/meta-downstream/build/tmp/work/raspberrypi4_64-poky-linux/rpi-autoboot/1.0-r1/sources/autoboot.txt': No such file or directory
	| WARNING: exit code 1 from a shell command.
	ERROR: Task (/home/gportay/src/meta-downstream/build/../meta-rauc-raspberrypi-firmware/recipes-bsp/bootfiles/rpi-autoboot.bb:do_deploy) failed with exit code '1'