Kconfig: image-fstypes: fix missing dependency on meta-downstream
This fixes commits:
 - 9fe4444c8e217b12c4721b4ad0476a98ac9f5b42
 - c2fca22850983f7fc91ca83674b12e0e9d2f72f6

This fixes missing dependency on qemux86-64 if selecting another QEMU
machine and dm-verity-img at the same time.

Fixes:

	ERROR: core-image-minimal-1.0-r0 do_image_wic: No kickstart files from WKS_FILES were found: efi-disk-dmverity-bootloader-config.wks.in  core-image-minimal.wks. Please set WKS_FILE or WKS_FILES appropriately.