update-bundle: fix slot file names
This fixes commit 6f11521ef7184f79802ff92739b325412df5e72f.

Fixes:

	ERROR: update-bundle-1.0-r0 do_configure: Failed to find source core-image-minimal-raspberrypi4-64.rootfs-p5.img
	ERROR: Logfile of failure stored in: /home/gportay/src/meta-downstream/build/tmp/work/raspberrypi4_64-poky-linux/update-bundle/1.0-r0/temp/log.do_configure.212967
	ERROR: Task (/home/gportay/src/meta-downstream/build/../meta-rauc-community/meta-rauc-raspberrypi/recipes-core/bundles/update-bundle.bb:do_configure) failed with exit code '1'