meta-rauc-raspberrypi-firmware: wic: fix deployment
This fixes commit 6f11521ef7184f79802ff92739b325412df5e72f.

This fixes the deployment of the WIC internal partitions by copying
every partitions found instead of hardcoded partitions p2 and p5.

Fixes:

	ERROR: core-image-minimal-1.0-r0 do_image_wic: Execution of '/home/gportay/src/meta-downstream/build/tmp/work/raspberrypi4_64-poky-linux/core-image-minimal/1.0/temp/run.do_image_wic.421393' failed with exit code 1
	ERROR: Logfile of failure stored in: /home/gportay/src/meta-downstream/build/tmp/work/raspberrypi4_64-poky-linux/core-image-minimal/1.0/temp/log.do_image_wic.421393
	Log data follows:
	| DEBUG: Executing python function extend_recipe_sysroot
	(...)
	DEBUG: Installed /home/gportay/src/meta-downstream/build/tmp/work/raspberrypi4_64-poky-linux/core-image-minimal/1.0/tmp-wic/rootfs_root.2.ext4 in partition 2, sectors 278528-821655, size 543128 sectors
	DEBUG: SourcePlugin: do_install_disk: disk: mmcblk0
	INFO: The new image(s) can be found here:
	  /home/gportay/src/meta-downstream/build/tmp/work/raspberrypi4_64-poky-linux/core-image-minimal/1.0/build-wic/sdimage-raspberrypi-202510170746-mmcblk0.direct

	The following build artifacts were used to create the image(s):
	  ROOTFS_DIR:                   /home/gportay/src/meta-downstream/build/tmp/work/raspberrypi4_64-poky-linux/core-image-minimal/1.0/rootfs
	  BOOTIMG_DIR:                  /home/gportay/src/meta-downstream/build/tmp/work/raspberrypi4_64-poky-linux/core-image-minimal/1.0/recipe-sysroot/usr/share
	  KERNEL_DIR:                   /home/gportay/src/meta-downstream/build/tmp/deploy/images/raspberrypi4-64
	  NATIVE_SYSROOT:               /home/gportay/src/meta-downstream/build/tmp/work/raspberrypi4_64-poky-linux/core-image-minimal/1.0/recipe-sysroot-native

	INFO: The image(s) were created using OE kickstart file:
	  /home/gportay/src/meta-downstream/build/../meta-raspberrypi/wic/sdimage-raspberrypi.wks
	cp: cannot stat '/home/gportay/src/meta-downstream/build/tmp/work/raspberrypi4_64-poky-linux/core-image-minimal/1.0/build-wic/sdimage-raspberrypi-*.direct.p5': No such file or directory
	WARNING: exit code 1 from a shell command.
	ERROR: Task (/home/gportay/src/meta-downstream/build/../poky/meta/recipes-core/images/core-image-minimal.bb:do_image_wic) failed with exit code '1'