meta-security: select meta-oe
This fixes commit 74c2effd0715f8efdaec32c7186cb67ea73cd591.

This selects meta-oe.

Fixes:

	ERROR: Layer 'security' depends on layer 'openembedded-layer', but this layer is not enabled in your configuration