raspberrypi-firmware-rauc-bootloader-backend: use raspi-utils
The package userland has been marked as ancient and deprecated[1] two
years ago.

This replaces package userland to raspi-utils, and backports the recipe
to meta-backport-kirkstone from commit[2].

Fixes:

	ERROR: userland-20230419-r0 do_configure: Execution of '/home/gportay/src/meta-downstream/build/tmp/work/cortexa72-poky-linux/userland/20230419/temp/run.do_configure.220109' failed with exit code 1
	ERROR: Logfile of failure stored in: /home/gportay/src/meta-downstream/build/tmp/work/cortexa72-poky-linux/userland/20230419/temp/log.do_configure.220109
	Log data follows:
	| DEBUG: Executing python function extend_recipe_sysroot
	| NOTE: Direct dependencies are
	['/home/gportay/src/meta-downstream/build/../poky/meta/recipes-core/glibc/glibc_2.42.bb:do_populate_sysroot', '/home/gportay/src/meta-downstream/build/../poky/meta/recipes-devtools/cmake/cmake-native_4.1.0.bb:do_populate_sysroot', '/home/gportay/src/meta-downstream/build/../poky/meta/recipes-devtools/gcc/gcc-cross_15.2.bb:do_populate_sysroot', '/home/gportay/src/meta-downstream/build/../poky/meta/recipes-devtools/gcc/gcc-runtime_15.2.bb:do_populate_sysroot', '/home/gportay/src/meta-downstream/build/../poky/meta/recipes-devtools/quilt/quilt-native_0.69.bb:do_populate_sysroot', '/home/gportay/src/meta-downstream/build/../poky/meta/recipes-graphics/wayland/wayland_1.24.0.bb:do_populate_sysroot', 'virtual:native:/home/gportay/src/meta-downstream/build/../poky/meta/recipes-devtools/ninja/ninja_1.13.1.bb:do_populate_sysroot', 'virtual:native:/home/gportay/src/meta-downstream/build/../poky/meta/recipes-devtools/patch/patch_2.8.bb:do_populate_sysroot', 'virtual:native:/home/gportay/src/meta-downstream/build/../poky/meta/recipes-devtools/pkgconfig/pkgconfig_git.bb:do_populate_sysroot', 'virtual:native:/home/gportay/src/meta-downstream/build/../poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/home/gportay/src/meta-downstream/build/../poky/meta/recipes-graphics/wayland/wayland_1.24.0.bb:do_populate_sysroot']
	| NOTE: Installed into sysroot: []
	| NOTE: Skipping as already exists in sysroot: ['openssl', 'expat', 'gettext-minimal-native', 'glibc', 'libxcrypt', 'libxml2', 'ncurses', 'util-linux-libuuid', 'zlib', 'binutils-cross-aarch64', 'cmake-native', 'gcc-cross-aarch64', 'gcc-runtime', 'libgcc', 'libedit', 'libtool-native', 'm4-native', 'opkg-utils', 'python3', 'quilt-native', 'bzip2', 'texinfo-dummy-native', 'xz', 'wayland', 'linux-libc-headers', 'gdbm', 'libffi', 'sqlite3', 'openssl-native', 'expat-native', 'libxml2-native', 'ncurses-native', 'util-linux-libuuid-native', 'zlib-native', 'flex-native', 'gnu-config-native', 'libedit-native', 'make-native', 'ninja-native', 'patch-native', 'perl-native', 'pkgconfig-native', 'pseudo-native', 'python3-native', 'bzip2-native', 'xz-native', 'zstd-native', 'wayland-native', 'attr-native', 'gdbm-native', 'gmp-native', 'libffi-native', 'libmpc-native', 'mpfr-native', 're2c-native', 'sqlite3-native']
	| DEBUG: Python function extend_recipe_sysroot finished
	| DEBUG: Executing shell function do_configure
	| CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
	|   Compatibility with CMake < 3.5 has been removed from CMake.
	|
	|   Update the VERSION argument <min> value.  Or, use the <min>...<max>
	syntax
	|   to tell CMake that the project requires at least <min> but has been
	updated
	|   to work with policies introduced by <max> or earlier.
	|
	|   Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring
	anyway.
	|
	|
	| -- Configuring incomplete, errors occurred!
	| WARNING: exit code 1 from a shell command.
	ERROR: Task (/home/gportay/src/meta-downstream/build/../meta-raspberrypi/recipes-graphics/userland/userland_git.bb:do_configure) failed with exit code '1'

[1]: https://github.com/raspberrypi/userland/commit/96a7334ae9d5fc9db7ac92e59852377df63f1848
[2]: https://github.com/agherzan/meta-raspberrypi/commit/49a2d124890b96d28a590e52e6d0dd611c114f6b