kas: raspberrypi-firmware*: select use-autoboot
This selects missing option use-autoboot to fix the update-bundle build
issue below:

Fixes:

	ERROR: update-bundle-1.0-r0 do_configure: Failed to find source core-image-minimal-raspberrypi4-64.rootfs-p5.img
	ERROR: Logfile of failure stored in: /home/gportay/src/meta-downstream/build/tmp/work/raspberrypi4_64-poky-linux/update-bundle/1.0/temp/log.do_configure.683759
	ERROR: Task (/home/gportay/src/meta-downstream/build/../meta-rauc-community/meta-rauc-raspberrypi/recipes-core/bundles/update-bundle.bb:do_configure) failed with exit code '1'
	NOTE: Tasks Summary: Attempted 6626 tasks of which 6623 didn't need to be rerun and 1 failed.

	Summary: 1 task failed:
	  /home/gportay/src/meta-downstream/build/../meta-rauc-community/meta-rauc-raspberrypi/recipes-core/bundles/update-bundle.bb:do_configure
	    log: /home/gportay/src/meta-downstream/build/tmp/work/raspberrypi4_64-poky-linux/update-bundle/1.0/temp/log.do_configure.683759
	Summary: There was 1 ERROR message, returning a non-zero exit code.
	2025-10-17 14:05:06 - ERROR    - Command "/home/gportay/src/meta-downstream/poky/bitbake/bin/bitbake -c build update-bundle" failed with error 1