Kconfig: dm-verity-img: dm-verity-image-initramfs: remove ext4 wic IMAGE_FSTYPES
This fixes commit 3c3752ed8f97ea752d079e4b163f8d9b541f801a.

The initramfs recipes[1][2][3][4] set filesystem types IMAGE_FSTYPES[5]
from INITRAMFS_IMAGE_FSTYPES[6]:

	IMAGE_FSTYPES = "${INITRAMFS_FSTYPES}"

The image filesystem types uses the appending bitbake override syntax[7]
to create an additional image with a given format:

	IMAGE_FSTYPES:append = " wic"

That operator appends the value at variable expansion time, and thus,
causes initramfs recipes to build an image with formats reserved for
final image instead of traditional initramfs file format.

The example below results in INITRAMFS_FSTYPES = "cpio.gz wic", and
thus, may create a circular dependency chain and throw errors attached
below if initramfs is part the final image:

	INITRAMFS_FSTYPES ?= "cpio.gz"
	IMAGE_FSTYPES = "${INITRAMFS_FSTYPES}"
	IMAGE_FSTYPES:append = " wic"

As a workaround, this removes the current supported IMAGE_FSTYPE (i.e.
ext4 and wic) from the dm-verity-image-initramfs using the bitbake
removal override syntax[8] to ensure these image formats are unset for
that initramfs image recipe.

See 33effdba9d0869b24bca4816d4b43585584ec3ad.

Fixes:

	ERROR: core-image-minimal-1.0-r0 do_image_wic: Execution of '/home/gportay/src/meta-downstream/build/tmp/work/qemux86_64-oe-linux/core-image-minimal/1.0/temp/run.do_image_wic.1798892' failed with exit code 1
	ERROR: Logfile of failure stored in: /home/gportay/src/meta-downstream/build/tmp/work/qemux86_64-oe-linux/core-image-minimal/1.0/temp/log.do_image_wic.1798892

Or:

	ERROR: 5576 unbuildable tasks were found.
	These are usually caused by circular dependencies and any circular dependency chains found will be printed below. Increase the debug level to see a list of unbuildable tasks.

	Identifying dependency loops (this may take a short while)...

[1]: https://github.com/openembedded/openembedded-core/blob/3e862cddf28e58957b7c6d9c983fdb40eb5442fb/meta/recipes-core/images/core-image-initramfs-boot.bb#L17
[2]: https://github.com/openembedded/openembedded-core/blob/6440e1010ade2b4207879a2e8cd288bcd714a445/meta/recipes-core/images/core-image-minimal-initramfs.bb#L28
[3]: https://github.com/openembedded/openembedded-core/blob/89e2652ac83f2602d6dd60623a225b88dc67d288/meta/recipes-core/images/core-image-tiny-initramfs.bb#L25
[4]: https://git.yoctoproject.org/meta-security/tree/recipes-core/images/dm-verity-image-initramfs.bb?h=d6369c9aafc433b08f9bb000142b274738be3fb3#n19
[5]: https://docs.yoctoproject.org/ref-manual/variables.html#term-IMAGE_FSTYPES
[6]: https://docs.yoctoproject.org/ref-manual/variables.html#term-INITRAMFS_FSTYPES
[7]: https://docs.yoctoproject.org/bitbake/dev/bitbake-user-manual/bitbake-user-manual-metadata.html#appending-and-prepending-override-style-syntax
[8]: https://docs.yoctoproject.org/bitbake/dev/bitbake-user-manual/bitbake-user-manual-metadata.html#removal-override-style-syntax