Kconfig: add cyclonedx-export option
This adds option to inherit cyclonedx-export[1] to look for known CVEs
while building targets.

Note: CYCLONEDX_EXPORT_SBOM and CYCLONEDX_EXPORT_VEX renames SBOM and
VEX JSON files to support multiple image targets (see wrynose change[2]
that overseedes[3]):

	NOTE: Executing Tasks
	ERROR: q2-system-1.0-r0 do_deploy_cyclonedx: Recipe q2-system is trying to install files into a shared area when those files already exist. The files and the manifests listing them are:
	  /home/gportay/src/chauvin-arnoux/x1189-obsolescence-wifi/build/tmp/deploy/cyclonedx-export/bom.json
	    (matched in manifest-ca_imx6_dhcom_qualistar2-q2-recovery.deploy_cyclonedx)
	  /home/gportay/src/chauvin-arnoux/x1189-obsolescence-wifi/build/tmp/deploy/cyclonedx-export/vex.json
	    (matched in manifest-ca_imx6_dhcom_qualistar2-q2-recovery.deploy_cyclonedx)
	Please adjust the recipes so only one recipe provides a given file.
	ERROR: Logfile of failure stored in: /home/gportay/src/chauvin-arnoux/x1189-obsolescence-wifi/build/tmp/work/ca_imx6_dhcom_qualistar2-dhlinux-linux-gnueabi/q2-system/1.0/temp/log.do_deploy_cyclonedx.827943
	ERROR: Task (/home/gportay/src/chauvin-arnoux/x1189-obsolescence-wifi/build/../meta-qualistar/recipes-core/images/q2-system.bb:do_deploy_cyclonedx) failed with exit code '1'

Important: Even worse, it stages the task and breaks the rebuild:

	WARNING: Logfile for failed setscene task is /home/gportay/src/chauvin-arnoux/x1189-obsolescence-wifi/build/tmp/work/ca_imx6_dhcom_qualistar2-dhlinux-linux-gnueabi/q2-system/1.0/temp/log.do_deploy_cyclonedx_setscene.855209
	WARNING: Setscene task (/home/gportay/src/chauvin-arnoux/x1189-obsolescence-wifi/build/../meta-qualistar/recipes-core/images/q2-system.bb:do_deploy_cyclonedx_setscene) failed with exit code '1' - real task will be run instead

[1]: https://github.com/iris-GmbH/meta-cyclonedx/blob/scarthgap/README.md
[2]: https://github.com/iris-GmbH/meta-cyclonedx/commit/c4742de48dbae9951dc492a07a70a8b836860a84
[3]: https://github.com/iris-GmbH/meta-cyclonedx/commit/5c8b10d49f7cf0a372daf3ee814327163aa7659a