meta-rauc-raspberrypi-firmware: kirkstone: select meta-backport-kirkstone
This fixes commit 78fdbc5c33139e81cad57490cd4d31116e688f55.

This selects meta-backport-kirkstone[1] for kirkstone branch to ensure
rauc-conf recipe exists.

Fixes:

	ERROR: No recipes in default available for:
	  /home/gportay/src/meta-downstream/build/../meta-rauc-raspberrypi-firmware/recipes-core/rauc/rauc-conf.bbappend

[1]: https://github.com/rauc/meta-rauc/commit/d51bab8f760d48e082f3515606d2d1a18343f5d6