Allow to disable debug-tweaks
The image-feature debug-tweaks was dropped in walnascar[1].

This adds a very simple Kconfig architecture to allow to select the
debug-tweaks feature from kas menu.

Fixes:

	ERROR: Nothing PROVIDES 'core-image-minimal'
	core-image-minimal was skipped: 'debug-tweaks' in IMAGE_FEATURES (added via EXTRA_IMAGE_FEATURES) is not a valid image feature. Valid features: allow-empty-password allow-root-login bash-completion-pkgs dbg-pkgs dev-pkgs doc doc-pkgs eclipse-debug empty-root-password hwcodecs lic-pkgs nfs-client nfs-server overlayfs-etc package-management post-install-logging ptest-pkgs read-only-rootfs read-only-rootfs-delayed-postinsts serial-autologin-root splash src-pkgs ssh-server-dropbear ssh-server-openssh stateless-rootfs staticdev-pkgs tools-debug tools-profile tools-sdk tools-testapps weston x11 x11-base x11-sato